-- liquibase formatted sql

-- changeset Vlad:1737628883187-1
CREATE TABLE IF NOT EXISTS car (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    color VARCHAR(255) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    number VARCHAR(255) NOT NULL,
    CONSTRAINT pk_car PRIMARY KEY (id)
);

-- changeset Vlad:1737628883187-2
CREATE TABLE IF NOT EXISTS driver (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    gender VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    car_id BIGINT NOT NULL,
    CONSTRAINT pk_driver PRIMARY KEY (id)
);

-- changeset Vlad:1737628883187-3
ALTER TABLE car ADD CONSTRAINT uc_car_number UNIQUE (number);

-- changeset Vlad:1737628883187-4
ALTER TABLE driver ADD CONSTRAINT uc_driver_email UNIQUE (email);

-- changeset Vlad:1737628883187-5
ALTER TABLE driver ADD CONSTRAINT uc_driver_phone UNIQUE (phone);

