server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: passenger-service
          uri: lb://passenger-service
          predicates:
            - Path=/api/v1/passengers/**, /passenger-service/**

        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/api/v1/drivers/**, /api/v1/cars/**, /driver-service/**

        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/api/v1/ratings/**, /rating-service/**

        - id: ride-service
          uri: lb://ride-service
          predicates:
            - Path=/api/v1/rides/**, /ride-service/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:${EUREKA_PORT:8761}/eureka}
    register-with-eureka: ${REGISTER_WITH_EUREKA:true}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:true}

springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /passenger-service/v3/api-docs
        name: Passenger Service
      - url: /driver-service/v3/api-docs
        name: Driver Service
      - url: /rating-service/v3/api-docs
        name: Rating Service
      - url: /ride-service/v3/api-docs
        name: Ride Service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  elastic:
    metrics:
      export:
        enabled: ${ES_ENABLED:true}
        host: ${ES_HOST:http://localhost:9200}
        index: metrics
        step: ${ES_METRICS_STEP:10s}
        index-date-format: "yyyy.MM.dd"
        connect-timeout: ${ES_CONNECT_TIMEOUT:10s}
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_HOST:http://localhost:9411}/api/v2/spans
      export:
        enabled: true
  metrics:
    tags:
      app: ${spring.application.name}
    distribution:
      percentiles:
        http:
          server:
            requests: 0.5, 0.9, 0.95, 0.99
      percentiles-histogram:
        http:
          server:
            request: true

logging:
  logstash:
    enabled: ${LOGSTASH_ENABLED:true}
    destination: ${LOGSTASH_DESTINATION:localhost:5044}
