-- liquibase formatted sql

-- changeset Vlad:1738058972462-1
CREATE TABLE IF NOT EXISTS ride (
    ride_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    departure_address BIGINT NOT NULL,
    destination_address BIGINT NOT NULL,
    driver_id BIGINT NOT NULL,
    passenger_id BIGINT NOT NULL,
    ride_status INTEGER NOT NULL DEFAULT 1,
    ride_price DECIMAL(10,2) NOT NULL,
    distance DOUBLE PRECISION NOT NULL,
    pickup_time TIMESTAMP WITHOUT TIME ZONE,
    complete_time TIMESTAMP WITHOUT TIME ZONE,
    order_create_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_ride PRIMARY KEY (ride_id)
);

CREATE TABLE IF NOT EXISTS address (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address_name TEXT NOT NULL,
    address_latitude DOUBLE PRECISION NOT NULL,
    address_longitude DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_address PRIMARY KEY (address_id)
);

ALTER TABLE ride ADD CONSTRAINT fk_ride_departure_address FOREIGN KEY (departure_address) REFERENCES address(address_id);

ALTER TABLE ride ADD CONSTRAINT fk_ride_destination_address FOREIGN KEY (destination_address) REFERENCES address(address_id);
