name: Cab-aggregator
services:

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8089:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - cab-aggregator-application
    restart: always

  passenger_db:
    image: postgres:17-alpine
    ports:
      - "5436:5432"
    env_file:
      - .env
    volumes:
      - passenger-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PASSENGER_DB_USERNAME}
      POSTGRES_PASSWORD: ${PASSENGER_DB_PASSWORD}
      POSTGRES_DB: ${PASSENGER_DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PASSENGER_DB_USERNAME} -d passenger_db" ]
      interval: 10s
      retries: 5
    networks:
      - cab-aggregator-application

  driver_db:
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - driver-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DRIVER_DB_USERNAME}
      POSTGRES_PASSWORD: ${DRIVER_DB_PASSWORD}
      POSTGRES_DB: ${DRIVER_DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DRIVER_DB_USERNAME} -d driver_db" ]
      interval: 10s
      retries: 5
    networks:
      - cab-aggregator-application

  rating_db:
    image: postgres:17-alpine
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - rating-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${RATING_DB_USERNAME}
      POSTGRES_PASSWORD: ${RATING_DB_PASSWORD}
      POSTGRES_DB: ${RATING_DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${RATING_DB_USERNAME} -d rating_db" ]
      interval: 10s
      retries: 5
    networks:
      - cab-aggregator-application

  ride_db:
    image: postgres:17-alpine
    ports:
      - "5435:5432"
    env_file:
      - .env
    volumes:
      - ride-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${RIDE_DB_USERNAME}
      POSTGRES_PASSWORD: ${RIDE_DB_PASSWORD}
      POSTGRES_DB: ${RIDE_DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${RIDE_DB_USERNAME} -d ride_db" ]
      interval: 10s
      retries: 5
    networks:
      - cab-aggregator-application

  auth_db:
    image: postgres:17-alpine
    ports:
      - "5437:5432"
    env_file:
      - .env
    volumes:
      - auth-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${AUTH_DB_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTH_DB_USERNAME} -d auth_db" ]
      interval: 10s
      retries: 5
    networks:
      - cab-aggregator-application

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-date:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - cab-aggregator-application

  kafka:
    image: apache/kafka:4.0.2
    hostname: kafka
    volumes:
      - kafka-data:/tmp/kraft-combined-logs
    environment:
      - CLUSTER_ID=4L6g3nShT-eMCtK--X86sw
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1 || exit 1" ]
      interval: 10s
      timeout: 15s
      retries: 3
    networks:
      - cab-aggregator-application

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9090:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: "local-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_JMXPORT: 9999
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - cab-aggregator-application

  config-server:
    image: config-server:latest
    build:
      context: ../config-server
      dockerfile: ../docker/Dockerfile
      args:
        - SERVICE_NAME=config-server
    env_file:
      - .env
    environment:
      PROMETHEUS_ENABLED: ${PROMETHEUS_ENABLED:-true}
      TRACING_ENABLED: ${TRACING_ENABLED:-true}
      TEMPO_URL: ${TEMPO_URL:-http://tempo:4318/v1/traces}
    ports:
      - 8888:${CONFIG_SERVER_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://config-server:${CONFIG_SERVER_PORT}/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
    networks:
      - cab-aggregator-application

  eureka-server:
    image: eureka-server:latest
    build:
      context: ../eureka-server
      dockerfile: ../docker/Dockerfile
      args:
        - SERVICE_NAME=eureka-server
    env_file:
      - .env
    ports:
      - 8761:${EUREKA_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://eureka-server:${EUREKA_PORT}/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      start_period: 15s
      retries: 5
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - cab-aggregator-application

  passenger-service:
    image: passenger-service:latest
    build:
      context: ../passenger-service
      dockerfile: ../docker/Dockerfile
      args:
        - SERVICE_NAME=passenger-service
    env_file:
      - .env
    ports:
      - ${PASSENGER_SERVICE_PORT}:${PASSENGER_SERVICE_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://passenger-service:${PASSENGER_SERVICE_PORT}/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 45s
      retries: 5
    depends_on:
      passenger_db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - cab-aggregator-application

  auth-service:
    image: auth-service:latest
    build:
      context: ../auth-service
      dockerfile: ../docker/Dockerfile
      args:
        - SERVICE_NAME=auth-service
    env_file:
      - .env
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://passenger-service:${PASSENGER_SERVICE_PORT}/actuator/health || exit 1
      interval: 15s
      timeout: 5s
      start_period: 45s
      retries: 5
    depends_on:
      auth_db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - cab-aggregator-application

  driver-service:
    image: driver-service:latest
    build:
      context: ../driver-service
      dockerfile: ../docker/Dockerfile
      args:
        - SERVICE_NAME=driver-service
    env_file:
      - .env
    ports:
      - ${DRIVER_SERVICE_PORT}:${DRIVER_SERVICE_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://driver-service:${DRIVER_SERVICE_PORT}/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 45s
      retries: 5
    depends_on:
      driver_db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - cab-aggregator-application

  rating-service:
    image: rating-service:latest
    build:
      context: ../rating-service
      dockerfile: ../docker/Dockerfile
      args:
        - SERVICE_NAME=rating-service
    env_file:
      - .env
    ports:
      - ${RATING_SERVICE_PORT}:${RATING_SERVICE_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://rating-service:${RATING_SERVICE_PORT}/actuator/health || exit 1
      interval: 30s
      timeout: 15s
      start_period: 120s
      retries: 5
    depends_on:
      kafka:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      rating_db:
        condition: service_healthy
    networks:
      - cab-aggregator-application

  ride-service:
    image: ride-service:latest
    build:
      context: ../ride-service
      dockerfile: ../docker/Dockerfile
      args:
        - SERVICE_NAME=ride-service
    env_file:
      - .env
    ports:
      - ${RIDE_SERVICE_PORT}:${RIDE_SERVICE_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://ride-service:${RIDE_SERVICE_PORT}/actuator/health || exit 1
      interval: 30s
      timeout: 15s
      start_period: 120s
      retries: 5
    depends_on:
      ride_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - cab-aggregator-application


  api-gateway:
    image: api-gateway:latest
    build:
      context: ../api-gateway
      dockerfile: ../docker/Dockerfile
      args:
        - SERVICE_NAME=api-gateway
    restart: on-failure
    env_file:
      - .env
    ports:
      - 8080:${API_GATEWAY_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://api-gateway:${API_GATEWAY_PORT}/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 45s
      retries: 5
    depends_on:
      eureka-server:
        condition: service_healthy
      passenger-service:
        condition: service_healthy
      driver-service:
        condition: service_healthy
      ride-service:
        condition: service_healthy
      rating-service:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    networks:
      - cab-aggregator-application

  loki:
    image: grafana/loki:latest
    pull_policy: if_not_present
    command: -config.file=/etc/loki/loki.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki.yaml:/etc/loki/loki.yaml:ro
      - loki_data:/loki
    networks:
      - cab-aggregator-application

  prometheus:
    image: prom/prometheus:latest
    pull_policy: if_not_present
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - cab-aggregator-application

  tempo:
    image: grafana/tempo:latest
    pull_policy: if_not_present
    command: -config.file=/etc/tempo/tempo.yaml
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo/tempo.yaml:ro
      - tempo_data:/var/tempo
    networks:
      - cab-aggregator-application

  grafana:
    image: grafana/grafana:latest
    pull_policy: if_not_present
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      loki:
        condition: service_started
      prometheus:
        condition: service_started
      tempo:
        condition: service_started
    networks:
      - cab-aggregator-application

  promtail:
    image: grafana/promtail:latest
    pull_policy: if_not_present
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      - promtail_data:/tmp
    depends_on:
      loki:
        condition: service_started
    networks:
      - cab-aggregator-application

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_DB: postgres
      KC_DB_URL: ${AUTH_DB_URL}
      KC_DB_USERNAME: ${AUTH_DB_USERNAME}
      KC_DB_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - "8088:8080"
    command:
      - start-dev
      - --import-realm
    depends_on:
      auth_db:
        condition: service_healthy
    networks:
      - cab-aggregator-application

volumes:
  passenger-data:
  driver-data:
  rating-data:
  ride-data:
  redis-date:
  kafka-data:
  loki_data:
  tempo_data:
  grafana_data:
  prometheus_data:
  promtail_data:
  auth-data:
  keycloak_data:
  pgadmin_data:

networks:
  cab-aggregator-application:
    driver: bridge
