services:
  redis:
    image: redis:alpine
    container_name: redis
    deploy:
      resources:
        limits:
          memory: 64M

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 512M
      - --reserve-memory 0M
      - --check=false
      - --node-id 0                     # явно указать
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "rpk", "cluster", "health", "check"]
      interval: 10s
    deploy:
      resources:
        limits:
          memory: 768M

  logstash:
    image: logstash:7.9.1
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./elk-config/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./elk-config/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ls_data:/usr/share/logstash/data
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://logstash:9600"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: elasticsearch:7.17.10
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data/
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - xpack.security.enabled=false
    healthcheck:
      test: curl -f http://localhost:9200/_cluster/health || exit 1
      interval: 10s
      start_period: 45s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 512M

  kibana:
    image: kibana:7.17.10
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    deploy:
      resources:
        limits:
          memory: 512M

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=memory
      - MEMORY_MAX_TRACES=10000
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    deploy:
      resources:
        limits:
          memory: 256M

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    environment:
      KC_DB: dev-file
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      JAVA_OPTS_APPEND: "-Xms128m -Xmx512m"
    ports:
      - "8088:8080"
    deploy:
      resources:
        limits:
          memory: 768M

  dashboard:
    image: lissy93/dashy:latest
    container_name: dashy
    ports:
      - "8081:8080"
    volumes:
      - ./local-dashy-config.yml:/app/user-data/conf.yml # Тут описываются твои кнопки
    deploy:
      resources:
        limits:
          memory: 100M

volumes:
  elasticsearch_data:
  keycloak_data:
  ls_data:
