name: Cab-aggregator
services:

  passenger_db:
    image: postgres:17-alpine
    ports:
      - "5436:5432"
    env_file:
      - .env
    volumes:
      - passenger-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PASSENGER_DB_USERNAME}
      POSTGRES_PASSWORD: ${PASSENGER_DB_PASSWORD}
      POSTGRES_DB: passenger_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PASSENGER_DB_USERNAME} -d passenger_db" ]
      interval: 10s
      retries: 5
    networks:
      - cab-aggregator-application

  driver_db:
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - driver-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DRIVER_DB_USERNAME}
      POSTGRES_PASSWORD: ${DRIVER_DB_PASSWORD}
      POSTGRES_DB: driver_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DRIVER_DB_USERNAME} -d driver_db" ]
      interval: 10s
      retries: 5
    networks:
      - cab-aggregator-application

  rating_db:
    image: postgres:17-alpine
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - rating-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${RATING_DB_USERNAME}
      POSTGRES_PASSWORD: ${RATING_DB_PASSWORD}
      POSTGRES_DB: rating_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${RATING_DB_USERNAME} -d rating_db" ]
      interval: 10s
      retries: 5
    networks:
      - cab-aggregator-application

  ride_db:
    image: postgres:17-alpine
    ports:
      - "5435:5432"
    env_file:
      - .env
    volumes:
      - ride-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${RIDE_DB_USERNAME}
      POSTGRES_PASSWORD: ${RIDE_DB_PASSWORD}
      POSTGRES_DB: ride_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${RIDE_DB_USERNAME} -d ride_db" ]
      interval: 10s
      retries: 5
    networks:
      - cab-aggregator-application

  auth-db:
    image: postgres:17-alpine
    ports:
      - "5437:5432"
    env_file:
      - .env
    volumes:
      - auth-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${AUTH_DB_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: auth_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTH_DB_USERNAME} -d auth_db" ]
      interval: 10s
      retries: 5
    networks:
      - cab-aggregator-application

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-date:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - cab-aggregator-application

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - cab-aggregator-application

  kafka1:
    image: bitnami/kafka:3.4.1
    hostname: kafka1
    volumes:
      - kafka1-data:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
    healthcheck:
      test: kafka-topics.sh --bootstrap-server kafka1:9092 --list
      interval: 10s
      timeout: 15s
      retries: 3
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - cab-aggregator-application

  kafka2:
    image: bitnami/kafka:3.4.1
    hostname: kafka2
    volumes:
      - kafka2-data:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_BROKER_ID=2
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    healthcheck:
      test: kafka-topics.sh --bootstrap-server kafka2:9092 --list
      interval: 10s
      timeout: 15s
      retries: 3
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - cab-aggregator-application

  kafka3:
    image: bitnami/kafka:3.4.1
    hostname: kafka3
    volumes:
      - kafka3-data:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_BROKER_ID=3
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    healthcheck:
      test: kafka-topics.sh --bootstrap-server kafka3:9092 --list
      interval: 10s
      timeout: 15s
      retries: 3
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - cab-aggregator-application

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9090:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: "local-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
      KAFKA_CLUSTERS_0_JMXPORT: 9999
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    networks:
      - cab-aggregator-application

  eureka-server:
    image: eureka-server:latest
    build:
      context: ../eureka-server
      dockerfile: ../docker/Dockerfile
      args:
        - SERVICE_NAME=eureka-server
    env_file:
      - .env
    environment:
      - ES_HOST=${ES_HOST:-http://elasticsearch:9200}
      - LOGSTASH_DESTINATION=${LOGSTASH_DESTINATION:-logstash:5044}
      - EUREKA_PORT=${EUREKA_PORT}
    ports:
      - 8761:${EUREKA_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://eureka-server:${EUREKA_PORT}/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      start_period: 15s
      retries: 5
    depends_on:
      logstash:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - cab-aggregator-application

  passenger-service:
    image: passenger-service:latest
    build:
      context: ../passenger-service
      dockerfile: ../docker/Dockerfile
      args:
        - SERVICE_NAME=passenger-service
    env_file:
      - .env
    environment:
      - ES_HOST=${ES_HOST:-http://elasticsearch:9200}
      - LOGSTASH_DESTINATION=${LOGSTASH_DESTINATION:-logstash:5044}
      - SERVER_PORT=${PASSENGER_SERVICE_PORT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - PASSENGER_DB_URL=jdbc:postgresql://passenger_db:5432/passenger_db
      - PASSENGER_DB_USERNAME=${PASSENGER_DB_USERNAME}
      - PASSENGER_DB_PASSWORD=${PASSENGER_DB_PASSWORD}
      - KAFKA_URLS=kafka1:9092,kafka2:9092,kafka3:9092
      - EUREKA_DEFAULT_ZONE=http://eureka-server:${EUREKA_PORT}/eureka
    ports:
      - ${PASSENGER_SERVICE_PORT}:${PASSENGER_SERVICE_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://passenger-service:${PASSENGER_SERVICE_PORT}/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 45s
      retries: 5
    depends_on:
      passenger_db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    networks:
      - cab-aggregator-application

  auth-service:
    image: auth-service:latest
    build:
      context: ../auth-service
      dockerfile: ../docker/Dockerfile
      args:
        - SERVICE_NAME=auth-service
    env_file:
      - .env
    environment:
      - ES_HOST=${ES_HOST:-http://elasticsearch:9200}
      - LOGSTASH_DESTINATION=${LOGSTASH_DESTINATION:-logstash:5044}
      - SERVER_PORT=${AUTH_SERVICE_PORT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - AUTH_DB_URL=jdbc:postgresql://auth-db:5432/auth_db
      - AUTH_DB_USERNAME=${AUTH_DB_USERNAME}
      - AUTH_DB_PASSWORD=${AUTH_DB_PASSWORD}
      - KAFKA_URLS=kafka1:9092,kafka2:9092,kafka3:9092
      - EUREKA_DEFAULT_ZONE=http://eureka-server:${EUREKA_PORT}/eureka
      - KEYCLOAK_URL=${KEYClOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://passenger-service:${PASSENGER_SERVICE_PORT}/actuator/health || exit 1
      interval: 15s
      timeout: 5s
      start_period: 45s
      retries: 5
    depends_on:
      auth-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - cab-aggregator-application

  driver-service:
    image: driver-service:latest
    build:
      context: ../driver-service
      dockerfile: ../docker/Dockerfile
      args:
        - SERVICE_NAME=driver-service
    env_file:
      - .env
    environment:
      - ES_HOST=${ES_HOST:-http://elasticsearch:9200}
      - LOGSTASH_DESTINATION=${LOGSTASH_DESTINATION:-logstash:5044}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - SERVER_PORT=${DRIVER_SERVICE_PORT}
      - DRIVER_DB_URL=jdbc:postgresql://driver_db:5432/driver_db
      - DRIVER_DB_USERNAME=${DRIVER_DB_USERNAME}
      - DRIVER_DB_PASSWORD=${DRIVER_DB_PASSWORD}
      - EUREKA_DEFAULT_ZONE=http://eureka-server:${EUREKA_PORT}/eureka
      - KAFKA_URL=kafka1:9092,kafka2:9092,kafka3:9092
    ports:
      - ${DRIVER_SERVICE_PORT}:${DRIVER_SERVICE_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://driver-service:${DRIVER_SERVICE_PORT}/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 45s
      retries: 5
    depends_on:
      driver_db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    networks:
      - cab-aggregator-application

  rating-service:
    image: rating-service:latest
    build:
      context: ../rating-service
      dockerfile: ../docker/Dockerfile
      args:
        - SERVICE_NAME=rating-service
    env_file:
      - .env
    environment:
      - ES_HOST=${ES_HOST:-http://elasticsearch:9200}
      - LOGSTASH_DESTINATION=${LOGSTASH_DESTINATION:-logstash:5044}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - SERVER_PORT=${RATING_SERVICE_PORT}
      - RATING_DB_URL=jdbc:postgresql://rating_db:5432/rating_db
      - RATING_DB_USERNAME=${RATING_DB_USERNAME}
      - RATING_DB_PASSWORD=${RATING_DB_PASSWORD}
      - EUREKA_DEFAULT_ZONE=http://eureka-server:${EUREKA_PORT}/eureka
      - KAFKA_URL=kafka1:9092,kafka2:9092,kafka3:9092
    ports:
      - ${RATING_SERVICE_PORT}:${RATING_SERVICE_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://rating-service:${RATING_SERVICE_PORT}/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 45s
      retries: 5
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      rating_db:
        condition: service_healthy
    networks:
      - cab-aggregator-application

  ride-service:
    image: ride-service:latest
    build:
      context: ../ride-service
      dockerfile: ../docker/Dockerfile
      args:
        - SERVICE_NAME=ride-service
    env_file:
      - .env
    environment:
      - ES_HOST=${ES_HOST:-http://elasticsearch:9200}
      - LOGSTASH_DESTINATION=${LOGSTASH_DESTINATION:-logstash:5044}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - SERVER_PORT=${RIDE_SERVICE_PORT}
      - RIDE_DB_URL=jdbc:postgresql://ride_db:5432/ride_db
      - RIDE_DB_USERNAME=${RIDE_DB_USERNAME}
      - RIDE_DB_PASSWORD=${RIDE_DB_PASSWORD}
      - EUREKA_DEFAULT_ZONE=http://eureka-server:${EUREKA_PORT}/eureka
      - KAFKA_URLS=kafka1:9092,kafka2:9092,kafka3:9092
      - MAPBOX_API_KEY=${MAPBOX_API_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - ${RIDE_SERVICE_PORT}:${RIDE_SERVICE_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://ride-service:${RIDE_SERVICE_PORT}/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 45s
      retries: 5
    depends_on:
      ride_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    networks:
      - cab-aggregator-application


  api-gateway:
    image: api-gateway:latest
    build:
      context: ../api-gateway
      dockerfile: ../docker/Dockerfile
      args:
        - SERVICE_NAME=api-gateway
    restart: on-failure
    env_file:
      - .env
    environment:
      - ES_HOST=${ES_HOST:-http://elasticsearch:9200}
      - LOGSTASH_DESTINATION=${LOGSTASH_DESTINATION:-logstash:5044}
      - SERVER_PORT=${API_GATEWAY_PORT:-8080}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - EUREKA_DEFAULT_ZONE=http://eureka-server:${EUREKA_PORT}/eureka
    ports:
      - 8080:${API_GATEWAY_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://api-gateway:${API_GATEWAY_PORT}/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 45s
      retries: 5
    depends_on:
      eureka-server:
        condition: service_healthy
      passenger-service:
        condition: service_healthy
      driver-service:
        condition: service_healthy
      ride-service:
        condition: service_healthy
      rating-service:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    networks:
      - cab-aggregator-application

  elasticsearch:
    image: elasticsearch:7.9.1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data/
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl -f http://elasticsearch:9200/_cluster/health || exit 1
      interval: 10s
      start_period: 45s
      timeout: 5s
      retries: 10
    networks:
      - cab-aggregator-application

  kibana:
    image: kibana:7.9.1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    volumes:
      - kb_data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    networks:
      - cab-aggregator-application

  logstash:
    image: logstash:7.9.1
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./elk-config/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./elk-config/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ls_data:/usr/share/logstash/data
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600"]
      interval: 20s
      timeout: 15s
      retries: 5
      start_period: 30s
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - cab-aggregator-application

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://elasticsearch:9200
      - ES_INDEX=zipkin
      - ES_DATE_SEPARATOR=-
      - ES_INDEX_SHARDS=1
      - ES_INDEX_REPLICAS=0
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - cab-aggregator-application

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
    ports:
      - "8088:8080"
    command:
      - start-dev
      - --import-realm

volumes:
  passenger-data:
  driver-data:
  rating-data:
  ride-data:
  redis-date:
  kafka-data:
  elasticsearch_data:
  ls_data:
  kb_data:
  auth-data:
  kafka3-data:
  kafka2-data:
  kafka1-data:
  keycloak_data:

networks:
  cab-aggregator-application:
    driver: bridge
