name: Cab-aggregator
services:

  passenger_db:
    image: postgres:17-alpine
    ports:
      - "5436:5432"
    env_file:
      - .env
    volumes:
      - passenger-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PASSENGER_DB_USERNAME}
      POSTGRES_PASSWORD: ${PASSENGER_DB_PASSWORD}
      POSTGRES_DB: passenger_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PASSENGER_DB_USERNAME} -d passenger_db" ]
      interval: 10s
      retries: 5
    networks:
      - cab-aggregator-application

  driver_db:
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - driver-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DRIVER_DB_USERNAME}
      POSTGRES_PASSWORD: ${DRIVER_DB_PASSWORD}
      POSTGRES_DB: driver_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DRIVER_DB_USERNAME} -d driver_db" ]
      interval: 10s
      retries: 5
    networks:
      - cab-aggregator-application

  rating_db:
    image: postgres:17-alpine
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - rating-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${RATING_DB_USERNAME}
      POSTGRES_PASSWORD: ${RATING_DB_PASSWORD}
      POSTGRES_DB: rating_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${RATING_DB_USERNAME} -d rating_db" ]
      interval: 10s
      retries: 5
    networks:
      - cab-aggregator-application


  ride_db:
    image: postgres:17-alpine
    ports:
      - "5435:5432"
    env_file:
      - .env
    volumes:
      - ride-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${RIDE_DB_USERNAME}
      POSTGRES_PASSWORD: ${RIDE_DB_PASSWORD}
      POSTGRES_DB: ride_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${RIDE_DB_USERNAME} -d ride_db" ]
      interval: 10s
      retries: 5
    networks:
      - cab-aggregator-application

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-date:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - cab-aggregator-application

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - cab-aggregator-application

  kafka:
    image: bitnami/kafka:latest
    volumes:
      - kafka-data:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    healthcheck:
      test: kafka-topics.sh --bootstrap-server kafka:9092 --list
      interval: 10s
      timeout: 15s
      start_period: 10s
      retries: 3
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - cab-aggregator-application

  eureka-server:
    image: eureka-server:latest
    build:
      context: ../eureka-server
      dockerfile: ../docker/Dockerfile
      args:
        - SERVICE_NAME=eureka-server
    env_file:
      - .env
    environment:
      - EUREKA_PORT=${EUREKA_PORT}
    ports:
      - 8761:${EUREKA_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://eureka-server:${EUREKA_PORT}/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      start_period: 15s
      retries: 5
    networks:
      - cab-aggregator-application

  passenger-service:
    image: passenger-service:latest
    build:
      context: ../passenger-service
      dockerfile: ../docker/Dockerfile
      args:
        - SERVICE_NAME=passenger-service
    env_file:
      - .env
    environment:
      - SERVER_PORT=${PASSENGER_SERVICE_PORT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - PASSENGER_DB_URL=jdbc:postgresql://passenger_db:5432/passenger_db
      - PASSENGER_DB_USERNAME=${PASSENGER_DB_USERNAME}
      - PASSENGER_DB_PASSWORD=${PASSENGER_DB_PASSWORD}
      - KAFKA_URLS=kafka:9092
      - EUREKA_DEFAULT_ZONE=http://eureka-server:${EUREKA_PORT}/eureka
    ports:
      - ${PASSENGER_SERVICE_PORT}:${PASSENGER_SERVICE_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://passenger-service:${PASSENGER_SERVICE_PORT}/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      passenger_db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - cab-aggregator-application

  driver-service:
    image: driver-service:latest
    build:
      context: ../driver-service
      dockerfile: ../docker/Dockerfile
      args:
        - SERVICE_NAME=driver-service
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - SERVER_PORT=${DRIVER_SERVICE_PORT}
      - DRIVER_DB_URL=jdbc:postgresql://driver_db:5432/driver_db
      - DRIVER_DB_USERNAME=${DRIVER_DB_USERNAME}
      - DRIVER_DB_PASSWORD=${DRIVER_DB_PASSWORD}
      - EUREKA_DEFAULT_ZONE=http://eureka-server:${EUREKA_PORT}/eureka
      - KAFKA_URL=kafka:9092
    ports:
      - ${DRIVER_SERVICE_PORT}:${DRIVER_SERVICE_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://driver-service:${DRIVER_SERVICE_PORT}/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      driver_db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - cab-aggregator-application

  rating-service:
    image: rating-service:latest
    build:
      context: ../rating-service
      dockerfile: ../docker/Dockerfile
      args:
        - SERVICE_NAME=rating-service
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - SERVER_PORT=${RATING_SERVICE_PORT}
      - RATING_DB_URL=jdbc:postgresql://rating_db:5432/rating_db
      - RATING_DB_USERNAME=${RATING_DB_USERNAME}
      - RATING_DB_PASSWORD=${RATING_DB_PASSWORD}
      - EUREKA_DEFAULT_ZONE=http://eureka-server:${EUREKA_PORT}/eureka
      - KAFKA_URL=kafka:9092
    ports:
      - ${RATING_SERVICE_PORT}:${RATING_SERVICE_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://rating-service:${RATING_SERVICE_PORT}/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      kafka:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      rating_db:
        condition: service_healthy
    networks:
      - cab-aggregator-application

  ride-service:
    image: ride-service:latest
    build:
      context: ../ride-service
      dockerfile: ../docker/Dockerfile
      args:
        - SERVICE_NAME=ride-service
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - SERVER_PORT=${RIDE_SERVICE_PORT}
      - RIDE_DB_URL=jdbc:postgresql://ride_db:5432/ride_db
      - RIDE_DB_USERNAME=${RIDE_DB_USERNAME}
      - RIDE_DB_PASSWORD=${RIDE_DB_PASSWORD}
      - EUREKA_DEFAULT_ZONE=http://eureka-server:${EUREKA_PORT}/eureka
      - KAFKA_URLS=kafka:9092
      - MAPBOX_API_KEY=${MAPBOX_API_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - ${RIDE_SERVICE_PORT}:${RIDE_SERVICE_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://ride-service:${RIDE_SERVICE_PORT}/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      ride_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - cab-aggregator-application


  api-gateway:
    image: api-gateway:latest
    build:
      context: ../api-gateway
      dockerfile: ../docker/Dockerfile
      args:
        - SERVICE_NAME=api-gateway
    restart: on-failure
    env_file:
      - .env
    environment:
      - SERVER_PORT=${API_GATEWAY_PORT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - EUREKA_DEFAULT_ZONE=http://eureka-server:${EUREKA_PORT}/eureka
    ports:
      - 8080:${API_GATEWAY_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://api-gateway:${API_GATEWAY_PORT}/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      eureka-server:
        condition: service_healthy
      passenger-service:
        condition: service_healthy
      driver-service:
        condition: service_healthy
      ride-service:
        condition: service_healthy
      rating-service:
        condition: service_healthy
    networks:
      - cab-aggregator-application

volumes:
  passenger-data:
  driver-data:
  rating-data:
  ride-data:
  redis-date:
  kafka-data:

networks:
  cab-aggregator-application:
    driver: bridge
