services:
  - name: "Data & Messaging"
    icon: "fas fa-database"
    items:
      - title: "Kafka"
        subtitle: "Стриминг событий"
        icon: "fas fa-stream"
        url: "http://localhost:9092"

      - title: "Redis"
        subtitle: "Key-Value Store"
        icon: "fas fa-bolt"
        url: "http://localhost:6379"

  - name: "Observability"
    icon: "fas fa-eye"
    items:
      - title: "Kibana"
        subtitle: "Просмотр логов и дашбордов"
        icon: "fas fa-chart-area"
        url: "http://localhost:5601"
        endpoint: "http://localhost:5601/api/status" # Специальный эндпоинт Kibana

  - name: "Security & Auth"
    icon: "fas fa-shield-alt"
    items:
      - title: "Keycloak"
        subtitle: "Identity and Access Management"
        icon: "fas fa-user-lock"
        url: "http://localhost:8088"
        endpoint: "http://localhost:8088/health/live" # Для новых версий Keycloak (Quarkus)

  - name: "Infrastructure"
    icon: "fas fa-server"
    items:
      - title: "Elasticsearch"
        subtitle: "Поисковый движок"
        icon: "fas fa-search"
        url: "http://localhost:9200"
        endpoint: "http://localhost:9200/_cluster/health"
