appConfig:
  title: "Local Dev Stack"
  description: "Управление локальной инфраструктурой"
  theme: "dracula"
  statusCheck: false
  enableMultiTasking: true
  layout: "auto"

sections:
  - name: "Data & Messaging"
    icon: "fas fa-database"
    items:
      - title: "Redpanda (Kafka)"
        description: "Стриминг событий"
        icon: "si-foodpanda"
        url: "http://localhost:9092"
        statusCheck: false

      - title: "Redis"
        description: "Key-Value Store"
        icon: "sh-redis"
        url: "http://localhost:6379"
        statusCheck: false

  - name: "Observability"
    icon: "fas fa-eye"
    items:
      - title: "Kibana"
        description: "Просмотр логов и дашбордов"
        icon: "sh-kibana"
        url: "http://localhost:5601"
        statusCheck: false

      - title: "Jaeger"
        description: "Распределённая трассировка"
        icon: "si-jaeger"
        url: "http://localhost:16686"
        statusCheck: false

  - name: "Security & Auth"
    icon: "fas fa-shield-alt"
    items:
      - title: "Keycloak"
        description: "Identity and Access Management"
        icon: "sh-keycloak"
        url: "http://localhost:8088"
        statusCheck: false

  - name: "Infrastructure"
    icon: "fas fa-server"
    items:
      - title: "Elasticsearch"
        description: "Поисковый движок"
        icon: "sh-elasticsearch"
        url: "http://localhost:9200"
        statusCheck: false
