-- liquibase formatted sql

-- changeset Vlad:1738246713004-1
CREATE TABLE rating (
    rating_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    driver_id BIGINT NOT NULL,
    ride_id BIGINT NOT NULL,
    passenger_id BIGINT NOT NULL,
    rating FLOAT NOT NULL DEFAULT 5,
    comment TEXT,
    CONSTRAINT pk_rating PRIMARY KEY (rating_id),
    CONSTRAINT chk_rating_range CHECK (rating >= 0 AND rating <= 5)
);

