-- liquibase formatted sql

-- changeset Vlad:1738246713004-2
CREATE TABLE rating (
    rating_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rating DOUBLE PRECISION NOT NULL DEFAULT 5,
    rated_by INTEGER NOT NULL,
    comment TEXT,
    CONSTRAINT pk_rating PRIMARY KEY (rating_id),
    CONSTRAINT chk_rating_range CHECK (rating >= 0 AND rating <= 5),
    CONSTRAINT chk_rating_precision CHECK (rating = ROUND(rating::numeric, 2))
);