server:
  port: ${SERVER_PORT:5003}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: driver-service

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    listener:
      observation-enabled: true
    consumer:
      group-id: driver-ride-group
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
    topic:
      driver-busy-topic: driver.status.updated
      driver-create-topic: driver.create

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:${EUREKA_PORT:8761}/eureka}
    register-with-eureka: ${REGISTER_WITH_EUREKA:true}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:true}

springdoc:
  api-docs:
    path: /driver-service/v3/api-docs
  swagger-ui:
    path: /driver-service/swagger-ui.html

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  elastic:
    metrics:
      export:
        enabled: ${ES_ENABLED:true}
        host: ${ES_HOST:http://localhost:9200}
        index: metrics
        step: ${ES_METRICS_STEP:10s}
        index-date-format: "yyyy.MM.dd"
        connect-timeout: ${ES_CONNECT_TIMEOUT:10s}
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_HOST:http://localhost:9411}/api/v2/spans
      export:
        enabled: true
  metrics:
    tags:
      app: ${spring.application.name}
    distribution:
      percentiles:
        http:
          server:
            requests: 0.5, 0.9, 0.95, 0.99
      percentiles-histogram:
        http:
          server:
            request: true

logging:
  logstash:
    enabled: ${LOGSTASH_ENABLED:true}
    destination: ${LOGSTASH_DESTINATION:localhost:5044}
