spring:
  datasource:
    url: ${DRIVER_DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DRIVER_DB_USERNAME:postgres}
    password: ${DRIVER_DB_PASSWORD:1111}
    driver-class-name: ${DRIVER_DB_DRIVER:org.postgresql.Driver}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus