server:
  port: 5003

spring:
  profiles:
    active: dev
  application:
    name: driver-service

  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: "*"