server:
  port: 5003

spring:
  profiles:
    active: dev
  application:
    name: driver-service

  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    consumer:
      group-id: driver-ride-group
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer

    topic:
      driver-busy-topic: driver.status.updated

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/api-docs/swagger-ui.html
