server:
  port: 5003

spring:
  profiles:
    active: dev
  application:
    name: driver-service

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    consumer:
      group-id: driver-ride-group
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
    topic:
      driver-busy-topic: driver.status.updated

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:${EUREKA_PORT:8761}/eureka}
    register-with-eureka: ${REGISTER_WITH_EUREKA:true}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:true}

management:
  endpoints:
    web:
      exposure:
        include: "*"

openapi:
  service:
    title: driver-service doc
    version: 1.0.0
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /driver-service/v3/api-docs
  swagger-ui:
    path: /driver-service/swagger-ui.html

