server:
  port: ${EUREKA_PORT:8761}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  application:
    name: eureka-server

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:${server.port}/eureka}
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA:false}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:false}

management:
  endpoints:
    web:
      exposure:
        include: "*"