server:
  port: ${SERVER_PORT:5007}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: ride-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}
  kafka:
    bootstrap-servers: ${KAFKA_URLS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: ${KAFKA_RETRIES:3}
      acks: 1
      batch-size: 16384
      buffer-memory: 67108864
    topic:
      ride-completed-topic: ride.completed
      driver-busy-topic: driver.status.updated
      passenger-busy-topic: passenger.status.updated
    message:
      scheduler:
        fixed-rate: ${MESSAGE_SCHEDULER_FIXED-RATE:5000}

  cache:
    type: redis
    redis:
      time-to-live: ${REDIS_TTL:3000}
      key-prefix: "ride-service:"
      use-key-prefix: true

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 1s
        ignore-exceptions:
          - com.vlad.kuzhyr.rideservice.exception.CustomFeignException
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        ignore-exceptions:
          - com.vlad.kuzhyr.rideservice.exception.CustomFeignException
  timelimiter:
    configs:
      default:
        timeout-duration:
          seconds: 5

mapbox:
  api:
    routes:
      geocode: ${MAPBOX_GEOCODE_URL:https://api.mapbox.com/search/geocode/v6/forward}
      distance: ${MAPBOX_DISTANCE_URL:https://api.mapbox.com/directions/v5/mapbox/driving/{coordinates}}
    secret-key: ${MAPBOX_API_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:${EUREKA_PORT:8761}/eureka}
    register-with-eureka: ${REGISTER_WITH_EUREKA:true}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:true}

springdoc:
  api-docs:
    path: /ride-service/v3/api-docs
  swagger-ui:
    path: /ride-service/swagger-ui.html

management:
  tracing:
    sampling:
      probability: 1.0

  endpoints:
    web:
      exposure:
        include: "*"
  elastic:
    metrics:
      export:
        enabled: ${ES_ENABLED:true}
        host: ${ES_HOST:http://localhost:9200}
        index: metrics
        step: ${ES_METRICS_STEP:10s}
        index-date-format: "yyyy.MM.dd"
        connect-timeout: ${ES_CONNECT_TIMEOUT:10s}
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_HOST:http://localhost:9411}/api/v2/spans
      export:
        enabled: true
  metrics:
    tags:
      app: ${spring.application.name}
      host: ${java.rmi.server.hostname}
      application: ${spring.application.name}
    distribution:
      percentiles:
        http:
          server:
            requests: 0.5, 0.9, 0.95, 0.99
      percentiles-histogram:
        http:
          server:
            request: true

logging:
  logstash:
    enabled: ${LOGSTASH_ENABLED:true}
    destination: ${LOGSTASH_DESTINATION:localhost:5044}