server:
  port: ${SERVER_PORT:5007}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  application:
    name: ride-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}

  kafka:
    bootstrap-servers: ${KAFKA_URLS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: ${KAFKA_RETRIES:3}
      acks: 1
      batch-size: 16384
      buffer-memory: 67108864
    topic:
      ride-completed-topic: ride.completed
      driver-busy-topic: driver.status.updated
      passenger-busy-topic: passenger.status.updated
    message:
      scheduler:
        fixed-rate: ${MESSAGE_SCHEDULER_FIXED-RATE:3000}

  cache:
    type: redis
    redis:
      time-to-live: ${REDIS_TTL:3000}
      key-prefix: "ride-service:"
      use-key-prefix: true

resilience4j:
  retry:
    configs:
      default:
        registerHealthIndicator: true
        max-attempts: 3
        waitDuration: 500ms
        retryExceptions:
          - org.springframework.web.client.RestClientException

  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5000ms

mapbox:
  api:
    routes:
      geocode: ${MAPBOX_GEOCODE_URL:https://api.mapbox.com/search/geocode/v6/forward}
      distance: ${MAPBOX_DISTANCE_URL:https://api.mapbox.com/directions/v5/mapbox/driving/{coordinates}}
    secret-key: ${MAPBOX_API_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:${EUREKA_PORT:8761}/eureka}
    register-with-eureka: ${REGISTER_WITH_EUREKA:true}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:true}

springdoc:
  api-docs:
    path: /ride-service/v3/api-docs
  swagger-ui:
    path: /ride-service/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
