server:
  port: 5007

spring:
  profiles:
    active: dev
  application:
    name: ride-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          default:
            retryer: feign.Retryer$Default
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
  data:
    redis:
      port: 6379
      host: localhost

  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      acks: 1
      batch-size: 16384
      buffer-memory: 67108864
    topic:
      ride-completed-topic: ride.completed
      driver-busy-topic: driver.status.updated

  cache:
    type: redis
    redis:
      time-to-live: 60000
      key-prefix: "ride-service:"
      use-key-prefix: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/api-docs/swagger-ui.html

mapbox:
  api:
    secret-key: ${MAPBOX_API_KEY}

routes:
  passenger-service: http://localhost:5008/api/v1/passengers
  driver-service: http://localhost:5003/api/v1/drivers