spring:
  datasource:
    url: ${RIDE_DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${RIDE_DB_USERNAME:postgres}
    password: ${RIDE_DB_PASSWORD:1111}
    driver-class-name: ${RIDE_DB_DRIVER:org.postgresql.Driver}

management:
  endpoints:
    web:
      exposure:
        include: health, info
