spring:
  datasource:
    url: ${PASSENGER_DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${PASSENGER_DB_USERNAME:postgres}
    password: ${PASSENGER_DB_PASSWORD:1111}
    driver-class-name: ${PASSENGER_DB_DRIVER:org.postgresql.Driver}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
