server:
  port: 0

spring:
  profiles:
    active: dev
  application:
    name: passenger-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    driver-class-name: ${DB_DRIVER}

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /api/v1/passenger
  swagger-ui:
    path: /api/v1/passenger/swagger-ui.html