server:
  port: 0

spring:
  profiles:
    active: dev
  application:
    name: passenger-service
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"