plugins {
    id 'org.springframework.boot'
}

ext {
    mapstructVersion = '1.6.3'
    springdocVersion = '2.8.3'
    restAssuredVersion = '5.5.1'
    cucumberVersion = '7.11.1'
    schedlockVersion = '5.16.0'
    resilence4jVersion = "2.1.0"
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
    implementation 'org.springframework.cloud:spring-cloud-starter-loadbalancer'
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    implementation 'org.postgresql:postgresql'
    implementation 'org.liquibase:liquibase-core'
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdocVersion}"
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-api:${springdocVersion}"
    implementation "org.mapstruct:mapstruct:${mapstructVersion}"
    implementation "net.javacrumbs.shedlock:shedlock-spring:${schedlockVersion}"
    implementation "net.javacrumbs.shedlock:shedlock-provider-jdbc-template:${schedlockVersion}"
    implementation "io.github.resilience4j:resilience4j-spring-boot2:${resilence4jVersion}"
    implementation 'io.github.openfeign:feign-micrometer'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

    testImplementation 'org.testcontainers:postgresql'
    testImplementation 'org.testcontainers:kafka'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
    testImplementation 'org.springframework.cloud:spring-cloud-contract-wiremock'
    testImplementation "io.rest-assured:rest-assured:${restAssuredVersion}"
    testImplementation "io.cucumber:cucumber-java:${cucumberVersion}"
    testImplementation "io.cucumber:cucumber-junit:${cucumberVersion}"
    testImplementation "io.cucumber:cucumber-spring:${cucumberVersion}"
}