-- liquibase formatted sql

-- changeset Влад:1737108790202-1
CREATE TABLE IF NOT EXISTS passenger (
    passenger_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    is_enabled boolean not null default true,
    is_busy boolean not null default false,
    CONSTRAINT pk_passenger PRIMARY KEY (passenger_id)
);